dashboard/urls.py
from django.urls import path

from dashboard import views

urlpatterns = [

    path('demo/', views.Demo.as_view(), name='demo'),

    path('login/', views.Login.as_view(), name='login'),
    path('logout/', views.Logout.as_view(), name='logout'),

    path('', views.Home.as_view(), name='home'),
    path('schedule/', views.Schedule.as_view(), name='schedule'),
    path('time-off/', views.TimeOff.as_view(), name='time-off'),
    path('settings/', views.Settings.as_view(), name='settings'),

    # Basic Only
    path('availability/', views.Availability.as_view(), name='availability-page'),

    # Manager Only
    path('needs/', views.Needs.as_view(), name='needs'),
    path('user-list/', views.UserList.as_view(), name='user-list'),

    # START ajax #

    # Basic
    path('ajax/schedule-timeoff/', views.schedule_timeoff, name='schedule-timeoff'),
    path('ajax/availability/', views.availability, name='availability'),
    path('ajax/user-schedule/<str:start_date_string>/<str:end_date_string>/', views.user_schedule, name='user-schedule'),
    path('ajax/user-time-off/', views.update_user_time_off, name='user-time-off'),

    # Manager
    path('ajax/day-schedule/<str:date_string>/', views.day_schedule, name='day-schedule'),
    path('ajax/upcoming-time-off/<str:date_string>/', views.upcoming_time_off, name='upcoming-time-off'),
    path('ajax/upcoming-time-off/', views.update_time_off_request, name='update-time-off-request'),
    path('ajax/needs/', views.needs, name='needs-ajax'),
    path('ajax/full-schedule/<str:start_date_string>/<str:end_date_string>/', views.full_schedule, name='full-schedule'),
    path('ajax/full-schedule/', views.update_full_schedule, name='full-schedule'),
    path('ajax/saved-shifts/', views.get_saved_shifts, name='saved-shifts'),
    path('ajax/full-time-off/<str:date_string>/', views.full_time_off, name='full-time-off'),
    path('ajax/user-list/', views.get_user_list, name='get-user-list'),
    path('ajax/user-list/update/', views.update_user_status, name='update-user-status'),
    path('ajax/user-list/new/', views.new_user_on_list, name='add-new-user'),

    # END ajax #

    # Demo
    path('ajax/demo/shifts/', views.demo_get_saved_shifts, name='demo-shifts'),
    path('ajax/demo/users/', views.demo_get_user_list, name='demo-users'),
    path('ajax/demo/schedule/', views.demo_single_schedule, name='demo-schedule'),

]

webapp/urls.py
from django.urls import path

from webapp import views

urlpatterns = [

    # path('', views.temp_home),
    path('', views.home, name='absolute-home'),
    # path('works/', views.works, name='works'),
    # path('works-grid/', views.works_grid, name='works_grid'),
    # path('works-grid-no-text/', views.works_grid_no_text, name='works_grid_no_text'),
    path('about-hive/', views.about_hive, name='about-hive'),
    # path('blog/', views.blog, name='blog'),
    # path('about/', views.about, name='about'),
    # path('shop/', views.shop, name='shop'),
    path('contact/', views.contact, name='contact'),
    path('privacy/', views.privacy, name='privacy'),

    # ajax
    path('ajax/submit-email/', views.ajax_submit_email, name='submit-email'),

]

dashboard/forms.py
from django import forms
from firesdk.firebase_functions.firebaseconn import CompanyId, encode_email, get_user
from firebase_admin import auth


class LoginForm(forms.Form):
    company_id = forms.CharField(max_length=50, required=True)
    email = forms.EmailField(max_length=254, required=True)
    password = forms.CharField(widget=forms.PasswordInput(), required=True)
    token = forms.CharField(widget=forms.HiddenInput())
    remember_code = forms.BooleanField(required=False)

    def clean(self):
        cleaned_data = super().clean()
        company_id = cleaned_data.get('company_id')
        email = cleaned_data.get('email')
        token = cleaned_data.get('token')

        # check if company code is real.
        try:
            company_name = CompanyId.objects.get(company_code=company_id).name
        except CompanyId.DoesNotExist:
            raise forms.ValidationError('Invalid Credentials')

        # check if user exists in company
        user = get_user(company_name, encode_email(email))
        if not user:
            raise forms.ValidationError('Invalid Credentials')

        # validate token
        try:
            _ = auth.verify_id_token(token)
        except ValueError:
            raise forms.ValidationError('Invalid Credentials')

        return self.cleaned_data

dashboard/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse, Http404
from django.views import View

from .forms import LoginForm

from firesdk.firebase_functions.firebaseconn import *
from firesdk.util.utils import availability_to_dict, standard_to_military_time, unfilter_org_names, user_to_dict

from onboarding.onboard import add_single_user, email_single_user

from dashboard.custom.auth_utils import *

import json
from datetime import datetime, timedelta
from collections import defaultdict

# Create your views here.


class BaseDashboardView(View):

    @staticmethod
    def get_base_dict(request):
        session = request.session

        name = session['first_name'] + ' ' + session['last_name']
        position = session['position']
        email = session['email']

        base_dict = {'name': name, 'position': position, 'email': email}
        return base_dict


class Login(View):
    login_form = LoginForm

    def get(self, request):
        if is_authenticated(request):
            return HttpResponseRedirect('/hive/')

        remember_code = False
        try:
            remember_code = request.session['remember_code']
        except KeyError:
            pass

        if remember_code:
            # get company code
            try:
                company_code = request.session['company_id']
            except KeyError:
                company_code = '* Error getting code *'

            form = self.login_form(initial={'company_id': company_code, 'remember_code': True})
        else:
            form = self.login_form()

        return render(request, 'dashboard/login.html', {'login_form': form})

    def post(self, request):
        form = self.login_form(request.POST)

        if form.is_valid():
            cd = form.cleaned_data

            token = cd['token']
            email = cd['email']
            company_id = cd['company_id']
            checkbox = cd['remember_code']

            request.session['tk'] = token
            request.session['email'] = email
            request.session['company_id'] = company_id
            request.session['remember_code'] = checkbox

            company_name = get_company_name_by_company_code(company_id)
            user = get_user(company_name, encode_email(email))

            first_name = user['name']['first']
            last_name = user['name']['last']
            position = user['position']
            account_type_int = user['account_type']

            request.session['first_name'] = first_name
            request.session['last_name'] = last_name
            request.session['position'] = position
            request.session['account_type'] = account_type_int

            return HttpResponseRedirect('/hive/')
        else:
            return render(request, 'dashboard/login.html', {'login_form': form})


class Logout(View):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            del request.session['tk']
        except KeyError:
            pass

        try:
            del request.session['email']
        except KeyError:
            pass

        try:
            del request.session['first_name']
        except KeyError:
            pass

        try:
            del request.session['last_name']
        except KeyError:
            pass

        try:
            del request.session['position']
        except KeyError:
            pass

        try:
            if not request.session['remember_code']:
                try:
                    del request.session['company_id']
                except KeyError:
                    pass
        except KeyError:
            pass

        return render(request, 'dashboard/logout.html', {})


class Home(BaseDashboardView):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            account_type_int = request.session['account_type']
        except KeyError:
            raise Http404

        if account_type_int == 0:
            return render(request, 'dashboard/basic/index.html', self.get_base_dict(request))
        elif account_type_int == 1:
            return render(request, 'dashboard/manager/index.html', self.get_base_dict(request))
        else:
            raise Http404


class Schedule(BaseDashboardView):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            account_type_int = request.session['account_type']
        except KeyError:
            raise Http404

        if account_type_int == 0:
            return render(request, 'dashboard/basic/schedule.html', self.get_base_dict(request))
        elif account_type_int == 1:
            return render(request, 'dashboard/manager/schedule.html', self.get_base_dict(request))
        else:
            raise Http404


class TimeOff(BaseDashboardView):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            account_type_int = request.session['account_type']
        except KeyError:
            raise Http404

        if account_type_int == 0:
            raise Http404
        elif account_type_int == 1:
            try:
                company_id = request.session['company_id']
            except KeyError:
                raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING111')

            try:
                encoded_email = encode_email(request.session['email'])
            except KeyError:
                raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING222')

            company = get_company_name_by_company_code(company_id)
            user = get_user(company, encoded_email)
            department = user['primary_department']

            base_dict = self.get_base_dict(request)
            base_dict['department'] = unfilter_org_names(department)
            return render(request, 'dashboard/manager/timeoff.html', base_dict)
        else:
            raise Http404


class Availability(BaseDashboardView):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            account_type_int = request.session['account_type']
        except KeyError:
            raise Http404

        if account_type_int == 0:
            return render(request, 'dashboard/basic/availability.html', self.get_base_dict(request))
        elif account_type_int == 1:
            raise Http404
        else:
            raise Http404


class Needs(BaseDashboardView):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            account_type_int = request.session['account_type']
        except KeyError:
            raise Http404

        if account_type_int == 0:
            raise Http404
        elif account_type_int == 1:
            try:
                company_id = request.session['company_id']
            except KeyError:
                raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING111')

            try:
                encoded_email = encode_email(request.session['email'])
            except KeyError:
                raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING222')

            company = get_company_name_by_company_code(company_id)
            user = get_user(company, encoded_email)
            department = user['primary_department']

            base_dict = self.get_base_dict(request)
            base_dict['department'] = unfilter_org_names(department)

            return render(request, 'dashboard/manager/needs.html', base_dict)
        else:
            raise Http404


class UserList(BaseDashboardView):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            account_type_int = request.session['account_type']
        except KeyError:
            raise Http404

        if account_type_int == 0:
            raise Http404
        elif account_type_int == 1:
            try:
                company_id = request.session['company_id']
            except KeyError:
                raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING111')

            try:
                encoded_email = encode_email(request.session['email'])
            except KeyError:
                raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING222')

            company = get_company_name_by_company_code(company_id)
            user = get_user(company, encoded_email)

            return render(request, 'dashboard/manager/user_list.html', self.get_base_dict(request))
        else:
            raise Http404


class Settings(BaseDashboardView):

    def get(self, request):
        if not is_authenticated(request):
            return HttpResponseRedirect('/hive/login/')

        try:
            account_type_int = request.session['account_type']
        except KeyError:
            raise Http404

        if account_type_int == 0:
            return render(request, 'dashboard/basic/settings.html', self.get_base_dict(request))
        elif account_type_int == 1:
            return render(request, 'dashboard/manager/settings.html', self.get_base_dict(request))
        else:
            raise Http404


class Demo(View):

    def get(self, request):
        return render(request, 'dashboard/demo/demo.html', {})


# START ajax #

def schedule_timeoff(request):
    try:
        company_id = request.session['company_id']
    except KeyError:
        raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING111')

    try:
        encoded_email = encode_email(request.session['email'])
    except KeyError:
        raise ValueError('CHANGE THIS SHIT TO A 404 OR SOMETHING222')

templates/dashboard/empty_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>

    <meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<!-- Tell the browser to be responsive to screen width -->
  	<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />

  <!-- Facebook and Twitter integration -->
	<meta property="og:title" content=""/>
	<meta property="og:image" content=""/>
	<meta property="og:url" content=""/>
	<meta property="og:site_name" content=""/>
	<meta property="og:description" content=""/>
	<meta name="twitter:title" content="" />
	<meta name="twitter:image" content="" />
	<meta name="twitter:url" content="" />
	<meta name="twitter:card" content="" />

	<!-- Bootstrap 3.3.7 -->
  	<link rel="stylesheet" href="{% static 'css/dashboard/bootstrap/bootstrap.min.css' %}">
  	<!-- Font Awesome -->
  	<link rel="stylesheet" href="{% static 'css/dashboard/fonts/font-awesome.min.css' %}">
  	<!-- Ionicons -->
  	<link rel="stylesheet" href="{% static 'css/dashboard/icons/ionicons.min.css' %}">
  	<!-- Theme style -->
  	<link rel="stylesheet" href="{% static 'css/dashboard/base/AdminLTE.min.css' %}">
  	<!-- AdminLTE Skins. Choose a skin from the css/skins
	   folder instead of downloading all of them to reduce the load. -->
  	<link rel="stylesheet" href="{% static 'css/dashboard/skins/_all-skins.min.css' %}">

    {% block header %}
    {% endblock %}

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

</head>
<body class="hold-transition login-page">

    {% block content %}
    {% endblock %}

    <!-- Firebase Integration -->
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.9.1/firebase-auth.js"></script>

    <script>
        var config = {
            apiKey: "AIzaSyCLhMSeZyDrnwbHyS94MaQGDuFE1ha8eLc",
            authDomain: "testing-c86ad.firebaseapp.com",
            projectId: "testing-c86ad",
        };
        firebase.initializeApp(config);
    </script>

	<!-- jQuery 3 -->
	<script src="{% static 'js/dashboard/jquery/jquery.min.js' %}"></script>
	<!-- jQuery UI 1.11.4 -->
	<script src="{% static 'js/dashboard/jquery/jquery-ui.min.js' %}"></script>
	<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
	<script>
		$.widget.bridge('uibutton', $.ui.button);
	</script>
	<!-- Bootstrap 3.3.7 -->
	<script src="{% static 'js/dashboard/bootstrap/bootstrap.min.js' %}"></script>
	<!-- FastClick -->
	<script src="{% static 'js/dashboard/fastclick.js' %}"></script>
	<!-- AdminLTE App -->
	<script src="{% static 'js/dashboard/base/adminlte.min.js' %}"></script>

	{% block js_scripts %}
	{% endblock %}
	<!-- see dashboard.js for the creation of charts -->

</body>
</html>

templates/dashboard/empty_base_extension.html
<!DOCTYPE html>
<html>
{% extends 'dashboard/manager/base.html' %}
{% load staticfiles %}
<head>
  {% block header %}

  <title>AdminLTE 2 | General Form Elements</title>

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

  {% endblock %}
</head>
<body>
{% block content %}
{% endblock %}

{% block js_scripts %}
{% endblock %}

</body>
</html>

templates/dashboard/login.html
<!DOCTYPE html>
<html>
{% extends 'dashboard/empty_base.html' %}
{% load staticfiles %}
<head>
  {% block header %}
  <title>JBS | The Hive | Login</title>

  <!-- iCheck -->
  <link rel="stylesheet" href="{% static 'css/dashboard/utils/red.css' %}">
  <!-- Base -->
  <link rel="stylesheet" href="{% static 'css/dashboard/custom/base.css' %}">

  {% endblock %}
</head>
<body class="hold-transition login-page">
{% block content %}

<div class="login-box">
  <div class="login-logo logo-container">
    <a href="/"><img src="{% static 'images/logos/JBS-red-text.png' %}" height="100%" width="100%"></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body box">
    <p class="login-box-msg">Sign in to start your session</p>

    <form action="" method="post">
      <div class="form-group has-feedback">
        <input type="text" class="form-control" placeholder="Comapany Code" value="{{ login_form.company_id.value|default_if_none:'' }}" required name="company_id" maxlength="50" id="id_company_id">
        <span class="glyphicon glyphicon-barcode form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email" value="{{ login_form.email.value|default_if_none:'' }}" required name="email" maxlength="254" id="id_email">
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" required name="password" id="id_password">
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>

      {% if login_form.errors %}
        {% for field in login_form %}
          {% for error in field.errors %}
            <strong id="form-error" style="color:red">{{ error }}</strong>
          {% endfor %}
        {% endfor %}
      {% endif %}

      {% if login_form.non_field_errors %}
        {% for error in login_form.non_field_errors %}
          <strong id="form-error" style="color:red">{{ error }}</strong>
        {% endfor %}
      {% endif %}

      {% if login_form.errors or login_form.non_field_errors %}
      {% else %}
        <strong id="form-error" style="color:red"></strong>
      {% endif %}

      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <!--<input type="checkbox" class="form-control" name="remember_code" maxlength="254" id="id_remember_code">-->
              {{ login_form.remember_code }} Remember Company Code
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="button" id="form-button" class="btn btn-danger btn-block btn-flat">Sign In</button>
        </div>
        <button type="submit" id="hidden-button" hidden></button> <!-- User can easily find this hidden button. Make sure it is fail proof on backend. -->
        <input type="hidden" name="token" id="id_token">
        <!-- /.col -->
      </div>
      {% csrf_token %}
    </form>

    <a href="#">I forgot my password</a><br>

    <!--
    <div class="overlay" id="loading-indicator">
      <i class="fa fa-refresh fa-spin"></i>
    </div>-->

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->
{% endblock %}

{% block js_scripts %}
<!-- iCheck -->
<script src="{% static 'js/dashboard/utils/icheck.min.js' %}"></script>
<script>
  $(function () {
    $('input').iCheck({
      checkboxClass: 'icheckbox_square-red',
      radioClass: 'iradio_square-red',
      increaseArea: '20%' /* optional */
    });
  });
</script>
<script src="{% static 'js/dashboard/base/login.js' %}"></script>
{% endblock %}

</body>
</html>

templates/dashboard/logout.html
<!DOCTYPE html>
<html>
{% extends 'dashboard/empty_base.html' %}
{% load staticfiles %}
<head>
    {% block header %}
    <title>JBS | The Hive | Sign Out Successful</title>

    <!-- Base -->
    <link rel="stylesheet" href="{% static 'css/dashboard/custom/base.css' %}">

    {% endblock %}
</head>
<body class="hold-transition lockscreen">
{% block content %}

<!-- Automatic element centering -->
<div class="lockscreen-wrapper">
  <div class="lockscreen-logo logo-container">
    <a href="/"><img src="{% static 'images/logos/JBS-red-text.png' %}" height="100%" width="100%"></a>
  </div>

  <div class="help-block text-center">
    Sign out successful
  </div>
  <div class="text-center">
    <a href="/">Back to home</a> | <a href="{% url 'login' %}">Sign in again</a>
  </div>
</div>
<!-- /.center -->
{% endblock %}

{% block js_scripts %}
<!-- iCheck -->
<script src="{% static 'js/dashboard/base/logout.js' %}"></script>
{% endblock %}

</body>
</html>